#!/usr/bin/env bash

# Confine Opencode coding agent using bubblewrap.
# - drop all un-necessary privileges;
# - restrict filesystem access to current tree + shared config;
# - RO access to Opencode MCP + models authentication;
#
# Author: Guillaume Beraudo
# Licence: WTFPL

set -euo pipefail

TARGET_EXECUTABLE="`which opencode`"

if [ ! -f "${TARGET_EXECUTABLE}" ]; then
    echo "Executable missing : ${TARGET_EXECUTABLE}"
fi

# Save current-folder as that will be mapped in as read-write and the current folder we execute in.
CURRENT_FOLDER=${PWD}

# Resolve the real binary path (follows alternatives, flatpak, etc.)
REAL_COMMAND="$(readlink -n -e "$TARGET_EXECUTABLE")"


mkdir -p ~/.cache/opencode_bwrap/home
cp -rf ~/.gitconfig ~/.cache/opencode_bwrap/home/

COLORTERM="${COLORTERM:-truecolor}"
TERM="${TERM:-xterm-256color}"

# Build the full bwrap argument array
bwrap_args=(
    bwrap
    --unshare-all

    # Still allow networking after dropping other privileges.
    --share-net
    --unshare-pid

    --new-session
    --die-with-parent
    --as-pid-1
    --cap-drop ALL

    --proc /proc
    --dev  /dev

    --tmpfs /tmp
    --tmpfs /run
    --ro-bind-try /sys/block   /sys/block
    --ro-bind-try /sys/devices /sys/devices

    --clearenv
    --setenv COLORTERM "${COLORTERM}"
    --setenv TERM "${TERM}"
    --setenv LANG "${LANG}"
    --setenv PWD "${CURRENT_FOLDER}"
    --setenv HOME "${HOME}"
    --setenv PATH "${PATH}"

    --ro-bind-try /usr/bin    /usr/bin
    --ro-bind-try /usr/lib    /usr/lib
    --ro-bind-try /usr/lib64  /usr/lib64
    --ro-bind-try /usr/include /usr/include

    --symlink usr/bin   /bin
    --symlink usr/lib   /lib
    --symlink usr/lib64 /lib64


    --ro-bind-try /etc/hosts        /etc/hosts
    --ro-bind-try /etc/passwd        /etc/passwd
    --ro-bind-try /etc/group        /etc/group
    --ro-bind-try /etc/resolv.conf        /etc/resolv.conf
    --ro-bind-try /etc/ssl        /etc/ssl

    --bind-try "${HOME}/.cache/opencode_bwrap/home" "${HOME}"

    # Read-only access to opencode config
    --ro-bind-try "${HOME}/.config/opencode"  "${HOME}/.config/opencode"
    --ro-bind-try "${HOME}/.opencode" "${HOME}/.opencode"
    --ro-bind-try "${HOME}/.local/share/opencode/auth.json" "${HOME}/.local/share/opencode/auth.json"
    --ro-bind-try "${HOME}/.local/share/opencode/mcp-auth.json" "${HOME}/.local/share/opencode/mcp-auth.json"

    --bind-try    "${CURRENT_FOLDER}"             "${CURRENT_FOLDER}"
)

# For debugging
echo "${bwrap_args[@]}" -- /bin/bash

exec "${bwrap_args[@]}" -- "$REAL_COMMAND" "$@"
